### ISSUE TITLE
Text to add

### ISSUE THREAD

**Issue by tylerbeauchamp** [euclio/nourishbot#1]
:pizza: = Arsenal Pizza
:btb: = Bonetown Burgers
:cnr: = Chicken & Rice
:burrito: = Chipotle
:rice: = Gogi
:athena: = Nourish
:flag-th: = O-sha
:handbag: = Packed lunch
:peach: = Peach

**Comment by euclio** [comment]
Closing this as the lunch train system now uses a bot :)
